apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: salesforce-tools
  description: A collection of tools used to work with Salesforce and CDS products
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
